export const AUTHENTICATED = 'AUTHENTICATED';
export const RETRIEVE_USERS = 'RETRIEVE_USERS';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_NAME_COLOR = 'CHANGE_NAME_COLOR';

export const TYPE_MESSAGE = 'TYPE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const RETRIEVE_MESSAGES = 'RETRIEVE_MESSAGES';
export const RETRIEVE_NEW_MESSAGE = 'RETRIEVE_NEW_MESSAGE';